workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.1.17f1"  # Change to a reliable version

    triggering:
      events:
        - push

    scripts:
      - name: Direct Download and Install Unity
        script: |
          echo "Attempting direct download and installation of Unity"
          UNITY_DOWNLOAD_URL="https://download.unity3d.com/download_unity/2021.1.17f1/Unity.pkg"  # Known version URL
          echo "Downloading Unity from $UNITY_DOWNLOAD_URL"
          curl -o /tmp/Unity.pkg "$UNITY_DOWNLOAD_URL"
          echo "Download complete, verifying /tmp directory contents"
          ls -l /tmp
          echo "Starting installation"
          sudo installer -pkg /tmp/Unity.pkg -target / || { echo "Installation failed"; exit 1; }
          echo "Unity installed successfully"

      - name: Build Project
        script: |
          /Applications/Unity/Hub/Editor/2021.1.17f1/Unity.app/Contents/MacOS/Unity -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
