workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.3.8f1"  # Adjust this based on your required Unity version

    triggering:
      events:
        - push

    scripts:
      - name: Download and Install Unity
        script: |
          UNITY_DOWNLOAD_URL="https://download.unity3d.com/download_unity/`$UNITY_VERSION`/Unity.pkg"
          curl -o Unity.pkg "$UNITY_DOWNLOAD_URL"
          sudo installer -pkg Unity.pkg -target /
      - name: Build Project
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -projectPath /workspace/Urdu-Learning-Game -quit -ba
