workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.3.8f1"  # Specify the Unity version directly

    triggering:
      events:
        - push

    scripts:
      - name: Install Unity via Unity Hub CLI
        script: |
          echo "Starting Unity installation using Unity Hub CLI"
          # Make sure Unity Hub is available and update if necessary
          brew install --cask unity-hub || true
          # Start Unity Hub and install the specified Unity version
          unity-hub install --version $UNITY_VERSION --default || { echo "Unity installation failed"; exit 1; }
          echo "Unity installed successfully"

      - name: Build Project
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
