workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.1.17f1"  # Specify a known Unity version

    triggering:
      events:
        - push

    scripts:
      - name: Check for Pre-installed Unity
        script: |
          echo "Checking for pre-installed Unity versions in /Applications/Unity/Hub/Editor"
          ls -l /Applications/Unity/Hub/Editor || echo "No Unity installations found in default path"
          # Try to locate Unity in standard paths
          UNITY_PATH=$(find /Applications/Unity/Hub/Editor -type d -name "$UNITY_VERSION" 2>/dev/null || echo "Unity not found")
          if [ "$UNITY_PATH" == "Unity not found" ]; then
            echo "No pre-installed Unity version found; exiting build."
            exit 1
          else
            echo "Using pre-installed Unity at $UNITY_PATH"
          fi
          
          # Verify the exact path to Unity executable for clarity
          UNITY_EXECUTABLE="$UNITY_PATH/Unity.app/Contents/MacOS/Unity"
          if [ ! -f "$UNITY_EXECUTABLE" ]; then
            echo "Unity executable not found at $UNITY_EXECUTABLE; exiting build."
            exit 1
          else
            echo "Unity executable found at $UNITY_EXECUTABLE"
          fi

      - name: Build Project
        script: |
          "$UNITY_EXECUTABLE" -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
