workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.1.17f1"  # Specify a known Unity version

    triggering:
      events:
        - push

    scripts:
      - name: Check for Pre-installed Unity
        script: |
          echo "Checking for pre-installed Unity versions"
          ls /Applications/Unity/Hub/Editor || echo "No Unity installations found in default path"
          # Try to locate Unity in standard paths
          UNITY_PATH=$(find /Applications/Unity/Hub/Editor -type d -name "2021.1.17f1" || echo "Unity not found")
          if [ "$UNITY_PATH" != "Unity not found" ]; then
            echo "Using pre-installed Unity at $UNITY_PATH"
          else
            echo "No pre-installed Unity version found; installation required but has been unsuccessful."
            exit 1
          fi

      - name: Build Project
        script: |
          "$UNITY_PATH/Unity.app/Contents/MacOS/Unity" -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
