workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.3.8f1"  # Adjust to your specific Unity version

    triggering:
      events:
        - push

    scripts:
      - name: Install Unity
        script: |
          # Install Unity using Unity Hub CLI for macOS
          brew install --cask unity-hub || true
          unity-hub install $UNITY_VERSION --default
      - name: Build Project
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
