workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.3.8f1"  # Adjust the version based on your needs

    triggering:
      events:
        - push

    scripts:
      - name: Install Unity
        script: |
          curl -o unity.tar.xz "https://download.unity3d.com/download_unity/`$UNITY_VERSION`/UnitySetup.tar.xz"
          mkdir unity-install
          tar -xf unity.tar.xz -C unity-install
          chmod +x unity-install/UnitySetup
          sudo unity-install/UnitySetup --unattended --install-location=/opt/Unity --download-location=unity-install --components=Unity
      - name: Build Project
        script: |
          /opt/Unity/Editor/Unity -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
