workflows:
  unity_build:
    name: Unity Build Workflow
    environment:
      vars:
        UNITY_VERSION: "2021.3.8f1"  # Adjust to a valid Unity version if necessary

    triggering:
      events:
        - push

    scripts:
      - name: Download and Install Unity
        script: |
          echo "Starting Unity installation"
          UNITY_DOWNLOAD_URL="https://download.unity3d.com/download_unity/2021.3.8f1/Unity.pkg"  # Manually specify the URL
          echo "Downloading Unity from $UNITY_DOWNLOAD_URL"
          curl -o Unity.pkg "$UNITY_DOWNLOAD_URL"
          echo "Download successful, starting installation"
          sudo installer -pkg ./Unity.pkg -target / || { echo "Installation failed"; exit 1; }
          echo "Unity installed successfully"

      - name: Build Project
        script: |
          /Applications/Unity/Hub/Editor/2021.3.8f1/Unity.app/Contents/MacOS/Unity -projectPath /workspace/Urdu-Learning-Game -quit -batchmode -nographics -buildTarget Win64 -executeMethod BuildScript.PerformBuild
